"""
This module contains all the string constants defined for this repo.
"""
"""
Regex declarations used in Web Info module.
"""
RE_VISITORS = "^> (.*?) visitors per day <$"
RE_IP_V6 = "IPv6.png'><a href='\/info\/whois6\/(.*?)'>"
RE_IP_LOCATION = "IP Location: <\/td> <td class='vmiddle'><span class='cflag (.*?)'><\/span><a href='\/view\/countries\/(.*?)\/Internet_Usage_Statistics_(.*?).html'>(.*?)<\/a>"
RE_REVERSE_DNS = "IP Reverse DNS (.*?)<\/b><\/div><div class='sval'>(.*?)<\/div>"
RE_HOSTING_COMPANY = "Hosting Company: <\/td><td valign='middle' class='bold'> <span class='nounderline'><a title='(.*?)"
RE_HOSTING_COMPANY_IP_OWNER_1 = "Hosting Company \/ IP Owner: <\/td><td valign='middle' class='bold'>  <span class='cflag (.*?)'><\/span> <a href='\/view\/web_hosting\/(.*?)'>(.*?)<\/a>"
RE_HOSTING_COMPANY_IP_OWNER_2 = "Hosting Company \/ IP Owner: <\/td><td valign='middle' class='bold'> <span class='nounderline'><a title='(.*?)"
RE_HOSTING_COMPANY_IP_OWNER = RE_HOSTING_COMPANY_IP_OWNER_1
RE_HOSTING_IP_RANGE = "IP Range <b>(.*?) - (.*?)<\/b><br>have <b>(.*?)<\/b>"
RE_HOSTING_ADDRESS = "Hosting Address: <\/td><td>(.*?)<\/td><\/tr>"
RE_OWNER_ADDRESS = "Owner Address: <\/td><td>(.*?)<\/td>"
RE_HOSTING_COUNTRY = "Hosting Country: <\/td><td><span class='cflag (.*?)'><\/span><a href='\/view\/countries\/(.*?)\/(.*?)'>(.*?)<\/a>"
RE_OWNER_COUNTRY = "Owner Country: <\/td><td><span class='cflag (.*?)'><\/span><a href='\/view\/countries\/(.*?)\/(.*?)'>(.*?)<\/a>"
RE_HOSTING_PHONE = "Hosting Phone: <\/td><td>(.*?)<\/td><\/tr>"
RE_OWNER_PHONE = "Owner Phone: <\/td><td>(.*?)<\/td><\/tr>"
RE_HOSTING_WEBSITE = "Hosting Website: <img class='cursor-help noprint left10' border='0' width='12' height='10' src='\/images\/tooltip.gif'><\/td><td><a href='\/(.*?)'>(.*?)<\/a><\/td>"
RE_OWNER_WEBSITE = "Owner Website: <img class='cursor-help noprint left10' border='0' width='12' height='10' src='\/(.*?)'><\/td><td><a href='\/(.*?)'>(.*?)<\/a>"
RE_CIDR = "CIDR:<\/td><td> (.*?)<\/td><\/tr>"
RE_OWNER_CIDR = """Owner CIDR: <\/td><td><span class='(.*?)'><a href="\/view\/ip_addresses\/(.*?)">(.*?)<\/a>\/(.*?)<\/span><\/td><\/tr>"""
RE_HOSTING_CIDR = """Hosting CIDR: <\/td><td><span class='(.*?)'><a href="\/view\/ip_addresses\/(.*?)">(.*?)<\/a>\/(.*?)<\/span><\/td><\/tr>"""